/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesRuleIdRouteImport } from './routes/rules.$ruleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/sources': typeof SourcesRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/sources': typeof SourcesRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/sources': typeof SourcesRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/allocation' | '/sources' | '/rules/$ruleId' | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allocation' | '/sources' | '/rules/$ruleId' | '/rules'
  id:
    '__root__' | '/' | '/allocation' | '/sources' | '/rules/$ruleId' | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  SourcesRoute: typeof SourcesRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  SourcesRoute: SourcesRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
